services:
      # FastAPI Backend Service
      - type: web
        name: haven-fastapi-backend
        env: python
        rootDir: backend # Points to the 'backend' directory in your repo
        # Enhanced buildCommand: Upgrade pip and setuptools first
        buildCommand: |
          echo "--- Upgrading pip and setuptools ---"
          pip install --upgrade pip setuptools wheel
          echo "--- Current PWD (should be /opt/render/project/src/backend) ---"
          pwd
          echo "--- LS -L in rootDir ---"
          ls -l
          echo "--- Attempting to cat requirements.txt ---"
          cat requirements.txt
          echo "--- Attempting pip install ---"
          pip install -r requirements.txt
        startCommand: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
        envVars:
          - key: FIREBASE_SERVICE_ACCOUNT_KEY_JSON_BASE64
            value: # Paste your base64 string here in Render Dashboard
          - key: ALGOLIA_API_KEY
            value: # Paste your Algolia Admin API Key here in Render Dashboard
          - key: ALGOLIA_APP_ID
            value: # Paste your Algolia Application ID here in Render Dashboard
          - key: BREVO_API_KEY
            value: # Paste your Brevo API Key here in Render Dashboard
          - key: INSTAMOJO_API_KEY
            value: # Paste your Instamojo API Key here in Render Dashboard
            # ... other env vars ...
          - key: INSTAMOJO_AUTH_TOKEN
            value: # Paste your Instamojo Auth Token here in Render Dashboard
          - key: PYTHON_VERSION
            value: 3.10.13

      # Streamlit Frontend Service (Apply similar changes if it also fails with setuptools)
      - type: web
        name: haven-streamlit-frontend
        env: python
        rootDir: frontend # <-- SIMPLIFIED THIS LINE!
        buildCommand: |
          echo "--- Upgrading pip and setuptools ---"
          pip install --upgrade pip setuptools wheel
          echo "--- Current PWD (should be /opt/render/project/src/frontend) ---"
          pwd
          echo "--- LS -L in rootDir ---"
          ls -l
          echo "--- Attempting to cat requirements.txt ---"
          cat requirements.txt
          echo "--- Attempting pip install ---"
          pip install -r requirements.txt
        startCommand: streamlit run front_main.py --server.port $PORT --server.address 0.0.0.0 --server.enableCORS false --server.enableXsrfProtection false
        envVars:
          - key: FASTAPI_BACKEND_URL
            value: ${haven-fastapi-backend.url}
          - key: FIREBASE_SERVICE_ACCOUNT_KEY_JSON_BASE64
            value: # You will paste the base64 string here in Render Dashboard
          - key: ALGOLIA_API_KEY
            value: # Paste your Algolia Admin API Key here in Render Dashboard
          - key: ALGOLIA_APP_ID
            value: # Paste your Algolia Application ID here in Render Dashboard
          - key: BREVO_API_KEY
            value: # Paste your Brevo API Key here in Render Dashboard
          - key: INSTAMOJO_API_KEY
            value: # Paste your Instamojo API Key here in Render Dashboard
          - key: INSTAMOJO_AUTH_TOKEN
            value: # Paste your Instamojo Auth Token here in Render Dashboard
          - key: PYTHON_VERSION
            value: 3.10.13
    